name: Python application

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: bookstore_dev_db
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U bookstore_dev"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DEBUG: "True"
      SECRET_KEY: "ci-secret-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_DATABASE: "bookstore_dev_db"
      SQL_USER: "bookstore_dev"
      SQL_PASSWORD: "bookstore_dev"
      SQL_HOST: "localhost"
      SQL_PORT: "5432"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          pip install poetry==2.1.4

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Run tests
        run: poetry run pytest